carts/urls.py
from django.urls import path
from carts import views

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add-cart/<int:product_id>/',views.add_cart, name='add-cart'),
     path('checkout/', views.checkout, name='checkout'),

    path('remove-cart/<int:product_id>/<int:cart_item_id>/',views.remove_cart, name='remove-cart'),
    path('remove-cart-item/<int:product_id>/<int:cart_item_id>/',views.remove_cart_item, name='remove-cart-item'),
    
]

greatkart/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', include('admin_honeypot.urls',namespace='admin_honeypot')),
    path('admin-login/', admin.site.urls),
    path('',views.home, name="home"),
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
    path('accounts/', include('accounts.urls')),
    path('orders/', include('orders.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

store/urls.py
from . import views
from django.urls import path


urlpatterns = [
    
    path('',views.store, name="store"),
    path('search/',views.search, name="search"),
    path('submit_review/<int:product_id>/', views.submit_review, name='submit_review'),
    path('<slug:category_slug>/',views.store, name='product_by_category'),
    path('<slug:category_slug>/<slug:product_slug>',views.product_detail, name='product_detail'),
    
] 

store/models.py
from django.db import models
from django.urls import reverse
from cataegory.models import Category
from accounts.models import Account
from django.db.models import Avg,Count

# Create your models here.
class Product(models.Model):
    product_name = models.CharField(max_length=200,unique=True)
    slug = models.SlugField(max_length=200,unique=True)
    description = models.TextField(max_length=200,blank=True)
    price = models.IntegerField()
    images = models.ImageField(upload_to='photos/products')
    stock = models.IntegerField()
    is_available = models.BooleanField(default=True)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse('product_detail',args=[self.category.slug, self.slug])

    def __str__(self):
        return self.product_name

    def averageReview(self):
        reviews = ReviewRating.objects.filter(product=self,status=True).aggregate(average=Avg('rating'))
        avg = 0
        if reviews['average'] is not None:
            avg = float(reviews['average'])
        return avg
    
    def countReview(self):
        reviews = ReviewRating.objects.filter(product=self,status=True).aggregate(count=Count('id'))
        count = 0
        if reviews['count'] is not None:
            count = int(reviews['count'])
        return count

class VariationManager(models.Manager):
    def color(self):
        return super(VariationManager,self).filter(variation_category='color', is_active=True)

    def size(self):
        return super(VariationManager,self).filter(variation_category='size', is_active=True)
        

variation_category_choice = (
    ('color','color'),
    ('size','size'),
)
class Variation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation_category = models.CharField(max_length=100,choices=variation_category_choice)
    variation_value = models.CharField(max_length=40)
    is_active = models.BooleanField(default=True)
    created_date = models.DateTimeField(auto_now_add=True)

    objects = VariationManager()

    def __str__(self):
        return self.variation_value


class ReviewRating(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    subject = models.CharField(max_length=100, blank=True)
    review = models.TextField(max_length=500, blank=True)
    rating = models.FloatField()
    ip = models.CharField(max_length=20, blank=True)
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject

class ProductGallery(models.Model):
    product = models.ForeignKey(Product, default=None, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='store/products', max_length=255)

    def __str__(self):
        return self.product.product_name

    class Meta:
        verbose_name = 'productgallery'
        verbose_name_plural = 'product gallery'

store/forms.py
from django import forms
from .models import *



class ReviewForm(forms.ModelForm):
    class Meta:
        model = ReviewRating
        fields = ['subject', 'review', 'rating']

store/views.py
from django.shortcuts import render,get_object_or_404,redirect
from store.models import *
from cataegory.models import Category
from carts.models import CartItem
from orders.models import * 
from django.contrib import messages
from carts.views import _cart_id
from django.core.paginator import EmptyPage,PageNotAnInteger,Paginator
from django.db.models import Q
from .forms import *

# Create your views here.

def store(request,category_slug=None):
    categories = None
    products = None

    if category_slug != None:
        categories = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category = categories, is_available=True)
        paginator = Paginator(products,6)
        page =request.GET.get('page')
        paged_products = paginator.get_page(page)
        product_count = products.count()
    else:
        products = Product.objects.all().filter(is_available=True).order_by('id')
        paginator = Paginator(products,6)
        page =request.GET.get('page')
        paged_products = paginator.get_page(page)
        product_count = products.count()
    
    context = {
        'products': paged_products, """ Changing products:products to products:paged_products """
        'product_count':product_count
    }
    return render(request, 'store/store.html', context)


def product_detail(request, category_slug, product_slug):
    try:
        """category__slug will take slug from category model """
        single_product = Product.objects.get(category__slug=category_slug , slug= product_slug)
        in_cart = CartItem.objects.filter(cart__cart_id = _cart_id(request), product=single_product).exists()
      

    except Exception as e:
        raise e

    if request.user.is_authenticated:
        try:
            orderproduct = OrderProduct.objects.filter(user=request.user,product_id=single_product.id).exists()
        except OrderProduct.DoesNotExist:
            orderproduct = None
    else:
        orderproduct = None

    #Reviews
    reviews = ReviewRating.objects.filter(product_id= single_product.id,status=True)

     # Get the product gallery
    product_gallery = ProductGallery.objects.filter(product_id=single_product.id)

    context = {
        'single_product': single_product,
        'in_cart': in_cart,
        'orderproduct':orderproduct,
        'reviews':reviews,
        'product_gallery':product_gallery,
    }
    return render(request,'store/product_detail.html',context)



def search(request):
    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        if keyword:
            products = Product.objects.order_by('-created_date').filter(Q(description__icontains=keyword) | Q(product_name__icontains=keyword))
            product_count = products.count()
    context={
        'products':products,
        'product_count':product_count,
    }
    return render(request,'store/store.html',context)

def submit_review(request, product_id):
    url = request.META.get('HTTP_REFERER')
    if request.method == 'POST':
        try:
            reviews = ReviewRating.objects.get(user__id=request.user.id, product__id=product_id)
            form = ReviewForm(request.POST, instance=reviews)
            form.save()
            messages.success(request, 'Thank you! Your review has been updated.')
            return redirect(url)
        except ReviewRating.DoesNotExist:
            form = ReviewForm(request.POST)
            if form.is_valid():
                data = ReviewRating()
                data.subject = form.cleaned_data['subject']
                data.rating = form.cleaned_data['rating']
                data.review = form.cleaned_data['review']
                data.ip = request.META.get('REMOTE_ADDR')
                data.product_id = product_id
                data.user_id = request.user.id
                data.save()
                messages.success(request, 'Thank you! Your review has been submitted.')
                return redirect(url)

templates/store/checkout.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


<section class="section-content padding-y bg">
  <div class="container">

    <!-- ============================ COMPONENT 1 ================================= -->

    <div class="row">
      <aside class="col-lg-6">
        <div class="card">
          <div class="card-body">
            <h4 class="card-title mb-4">Billing Address</h4>
            <form action="{% url 'place_orders' %}" method="POST">
              {% csrf_token %}
              <div class="form-row">
                <div class="col form-group">
                  <label for="">First Name</label>
                  <input type="text" name="first_name" class="form-control" required>
                </div>
                <div class="col form-group">
                  <label for="">Last Name</label>
                  <input type="text" name="last_name" class="form-control" required>
                </div>
              </div>
              <div class="form-row">
                <div class="col form-group">
                  <label for="">Email</label>
                  <input type="email" name="email" class="form-control" required>
                </div>
                <div class="col form-group">
                  <label for="">Phone Number</label>
                  <input type="text" name="phone" class="form-control" required>
                </div>
              </div>
              <div class="form-row">
                <div class="col form-group">
                  <label for="">Address Line 1</label>
                  <input type="text" name="address_line_1" class="form-control" required>
                </div>
                <div class="col form-group">
                  <label for="">Address Line 2</label>
                  <input type="text" name="address_line_2" class="form-control">
                </div>
              </div>
              <div class="form-row">
                <div class="col form-group">
                  <label for="">City</label>
                  <input type="text" name="city" class="form-control" required>
                </div>
                <div class="col form-group">
                  <label for="">State</label>
                  <input type="text" name="state" class="form-control" required>
                </div>
                <div class="col form-group">
                  <label for="">Country</label>
                  <input type="text" name="country" class="form-control" required>
                </div>
              </div>
              <div class="form-row">
                <label for="">Order Note</label>
                <textarea name="order_note" rows="2" class="form-control"></textarea>
              </div>


          </div>
        </div> <!-- card.// -->

      </aside> <!-- col.// -->
      <aside class="col-lg-6">

        <div class="card">
          <div class="card-body">
            <table class="table table-borderless table-shopping-cart">
              <thead class="text-muted">
                <tr class="small text-uppercase">
                  <th scope="col">Product</th>
                  <th scope="col" width="120">Quantity</th>
                  <th scope="col" width="120">Price</th>

                </tr>
              </thead>
              <tbody>

                {% for cart_item in cart_items %}
                <tr>
                  <td>
                    <figure class="itemside align-items-center">
                      <div class="aside"><img src="{{ cart_item.product.images.url }}" class="img-sm"></div>
                      <figcaption class="info">
                        <a href="{{ cart_item.product.get_url }}" class="title text-dark">{{ cart_item.product.product_name }}</a>
                        <p class="text-muted small">
                          {% if cart_item.variations.all %}
                          {% for item in cart_item.variations.all %}
                          {{ item.variation_category | capfirst }} : {{ item.variation_value | capfirst }} <br>
                          {% endfor %}
                          {% endif %}
                        </p>
                      </figcaption>
                    </figure>
                  </td>
                  <td>
                    <!-- col.// -->
                    <label for="">{{cart_item.quantity}}</label>
                  </td>
                  <td>
                    <div class="price-wrap">
                      <var class="price">$ {{ cart_item.sub_total }}</var>
                      <small class="text-muted"> $ {{ cart_item.product.price }} each </small>
                    </div> <!-- price-wrap .// -->
                  </td>

                </tr>
                {% endfor %}

              </tbody>
            </table>

            <button type="submit" name="submit" class="btn btn-primary btn-block">Place Order</button>
            <a href="{% url 'store' %}" class="btn btn-light btn-block">Continue Shopping</a>
            </form>
          </div> <!-- card-body.// -->
        </div> <!-- card.// -->


      </aside> <!-- col.// -->


    </div> <!-- row.// -->

    <!-- ============================ COMPONENT 1 END .// ================================= -->

  </div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}

templates/store/product_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<section class="section-content padding-y bg">
  <div class="container">

    <!-- ============================ COMPONENT 1 ================================= -->
    <div class="card">
      <div class="row no-gutters">
        <aside class="col-md-6">
          <article class="gallery-wrap">
            <div class="img-big-wrap mainImage">
              <center><img src="{{ single_product.images.url }}"></center>
            </div> <!-- img-big-wrap.// -->

          </article> <!-- gallery-wrap .end// -->
          <ul class="thumb">
            <li>
                <a href="{{ single_product.images.url }}" target="mainImage"><img src="{{ single_product.images.url }}" alt="Product Image"></a>
                {% for i in product_gallery %}
                <a href="{{i.image.url}}" target="mainImage"><img src="{{i.image.url}}" alt="Product Image"></a>
                {% endfor %}
            </li>
          </ul>
        </aside>
        <main class="col-md-6 border-left">
          <form action="{% url 'add-cart' single_product.id %}" method="POST">
            {% csrf_token %}

            <article class="content-body">

              <h2 class="title">{{ single_product.product_name }}</h2>
              <div class="rating-star">
                <span>
                  <i class="fa fa-star{% if single_product.averageReview < 0.5 %}-o{% elif single_product.averageReview < 1 and single_product.averageReview >= 0.5 %}-half-o {% endif %} aria-hidden="true"></i>
                  <i class="fa fa-star{% if single_product.averageReview < 1.5 %}-o{% elif single_product.averageReview < 2 and single_product.averageReview >= 1.5 %}-half-o {% endif %} aria-hidden="true"></i>
                  <i class="fa fa-star{% if single_product.averageReview < 2.5 %}-o{% elif single_product.averageReview < 3 and single_product.averageReview >= 2.5 %}-half-o {% endif %} aria-hidden="true"></i>
                  <i class="fa fa-star{% if single_product.averageReview < 3.5 %}-o{% elif single_product.averageReview < 4 and single_product.averageReview >= 3.5 %}-half-o {% endif %} aria-hidden="true"></i>
                  <i class="fa fa-star{% if single_product.averageReview < 4.5 %}-o{% elif single_product.averageReview < 5 and single_product.averageReview >= 4.5 %}-half-o {% endif %} aria-hidden="true"></i>
                  {{single_product.countReview}} Reviews
                </span>
              </div>
              
              <div class="mb-3">
                <var class="price h4">${{ single_product.price }}</var>
              </div>

              <p>{{ single_product.description }}</p>


              <hr>
              <div class="row">
                <div class="item-option-select">
                  <h6>Select Color</h6>
                  <select name="color" class="form-control" required>
                    <option value="" disabled selected>Choose Color</option>
                    {% for i in single_product.variation_set.color %}
                    <option value="{{ i.variation_value | lower }}">{{ i.variation_value | capfirst }}</option>
                    {% endfor %}
                  </select>
                </div>
              </div> <!-- row.// -->
              <div class="row">
                <div class="item-option-select">
                  <h6>Select Size</h6>
                  <select name="size" class="form-control">
                    <option value="" disabled selected>Choose Size</option>
                    {% for i in single_product.variation_set.size %}
                    <option value="{{ i.variation_value | lower  }}">{{ i.variation_value | capfirst }}</option>
                    {% endfor %}
                  </select>
                </div>
              </div> <!-- row.// -->
              <hr>
              {% if single_product.stock <= 0 %} <h5 class="btn btn-danger">Out of Stock</h5>
                {% else %}
                <!-- {% if in_cart %}
                <a href="#" class="btn  btn-success"> <span class="text">Added to
                  cart</span> <i class="fas fa-check"></i> </a>
                <a href="{% url 'cart' %}" class="btn btn-outline-secondary"> <span class="text">View Cart</span> <i class="fas fa-eye"></i> </a>
                {% else %}
                <button type="submit"  class="btn  btn-primary"> <span class="text">Add to
                    cart</span> <i class="fas fa-shopping-cart"></i> </button>
                {% endif %} -->
                <button type="submit" class="btn  btn-primary"> <span class="text">Add to
                    cart</span> <i class="fas fa-shopping-cart"> </i> </button>
                {% endif %}
            </article> <!-- product-info-aside .// -->
          </form>
        </main> <!-- col.// -->
      </div> <!-- row.// -->
    </div> <!-- card.// -->
    <!-- ============================ COMPONENT 1 END .// ================================= -->

    <br>

    <div class="row">
      <div class="col-md-9">

       
        <form action="{% url 'submit_review' single_product.id  %}" method="POST">
          {% csrf_token %}
          {% include 'includes/alerts.html' %}
          <h5>Write the Review</h5>
          <!-- {{single_product.averageReview}} -->
          <div>
            <!-- Rating stars -->
            <label>How do you rate this product?</label>
            <br>
            <div class="rate">
              <input type="radio" name="rating" id="rating10" value="5" required /><label for="rating10"
                title="5"></label>
              <input type="radio" name="rating" id="rating9" value="4.5" required /><label for="rating9" title="4.5"
                class="half"></label>
              <input type="radio" name="rating" id="rating8" value="4" required /><label for="rating8"
                title="4"></label>
              <input type="radio" name="rating" id="rating7" value="3.5" required /><label for="rating7" title="3.5"
                class="half"></label>
              <input type="radio" name="rating" id="rating6" value="3" required /><label for="rating6"
                title="3"></label>
              <input type="radio" name="rating" id="rating5" value="2.5" required /><label for="rating5" title="2.5"
                class="half"></label>
              <input type="radio" name="rating" id="rating4" value="2" required /><label for="rating4"
                title="2"></label>
              <input type="radio" name="rating" id="rating3" value="1.5" required /><label for="rating3" title="1.5"
                class="half"></label>
              <input type="radio" name="rating" id="rating2" value="1" required /><label for="rating2"
                title="1"></label>
              <input type="radio" name="rating" id="rating1" value="0.5" required /><label for="rating1" title="0.5"
                class="half"></label>
            </div>
            <div>
              Review Title:
              <input type="text" class="form-control" name="subject">
              <br>
              Review:
              <textarea name="review" rows="4" class="form-control"></textarea>

            </div>

          </div>
          <br>
          {% if user.is_authenticated %}
          {% if orderproduct %}
          <input type="submit" value="submit Review" class="btn btn-primary">
          {% else %}
          <p>You must be purchased this product to post the review.</p>
          {% endif %}
          {% else %}
          <p>You must be login inorder to review the item.<span><a href="{% url 'login' %}">Login now</a></span></p>
          {% endif %}

        </form>
        <header class="section-heading">
          <h3>Customer Reviews </h3>
          <div class="rating-star">
            <span>
              <i class="fa fa-star{% if single_product.averageReview < 0.5 %}-o{% elif single_product.averageReview < 1 and single_product.averageReview >= 0.5 %}-half-o {% endif %} aria-hidden="true"></i>
              <i class="fa fa-star{% if single_product.averageReview < 1.5 %}-o{% elif single_product.averageReview < 2 and single_product.averageReview >= 1.5 %}-half-o {% endif %} aria-hidden="true"></i>
              <i class="fa fa-star{% if single_product.averageReview < 2.5 %}-o{% elif single_product.averageReview < 3 and single_product.averageReview >= 2.5 %}-half-o {% endif %} aria-hidden="true"></i>
              <i class="fa fa-star{% if single_product.averageReview < 3.5 %}-o{% elif single_product.averageReview < 4 and single_product.averageReview >= 3.5 %}-half-o {% endif %} aria-hidden="true"></i>
              <i class="fa fa-star{% if single_product.averageReview < 4.5 %}-o{% elif single_product.averageReview < 5 and single_product.averageReview >= 4.5 %}-half-o {% endif %} aria-hidden="true"></i>
              {{single_product.countReview}} Reviews
            </span>
           
          </div>

        </header>
        <br>
        {% for review in reviews %}
        <article class="box mb-3">
          <div class="icontext w-100">

            <div class="text">
              <span class="date text-muted float-md-right">{{review.updated_at}}</span>
              <h6 class="mb-1">{{ review.user.full_name }}</h6>
              <div class="rating-star">
                <span>
                  <i class="fa fa-star{% if review.rating == 0.5 %}-half-o{% elif review.rating < 1 %}-o {% endif %} aria-hidden="true"></i>
                  <i class="fa fa-star{% if review.rating == 1.5 %}-half-o{% elif review.rating < 2 %}-o {% endif %} aria-hidden="true"></i>
                  <i class="fa fa-star{% if review.rating == 2.5 %}-half-o{% elif review.rating < 3 %}-o {% endif %} aria-hidden="true"></i>
                  <i class="fa fa-star{% if review.rating == 3.5 %}-half-o{% elif review.rating < 4 %}-o {% endif %} aria-hidden="true"></i>
                  <i class="fa fa-star{% if review.rating == 4.5 %}-half-o{% elif review.rating < 5 %}-o {% endif %} aria-hidden="true"></i>

                </span>
              </div>
            </div>
          </div> <!-- icontext.// -->
          <div class="mt-3">
            <h5>{{review.subject}}</h5>
            <p>
              {{review.review}}
            </p>
          </div>
        </article>

        {% endfor %}

      </div> <!-- col.// -->
    </div> <!-- row.// -->


  </div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock %}